title: "Jose Moreno Portfolio"
description: "Computer Science ePortfolio"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/

author:
  name: "Jose Moreno"
  avatar: "/assets/images/profile.jpg"
  bio: "Computer Science student focused on software engineering, artificial intelligence, and system design."
  location: "Texas, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Joseamorenojr"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com"
