title: "Jose Moreno Portfolio"
description: "Computer Science ePortfolio"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache

sass:
  style: compressed

include:
  - _pages

collections:
  projects:
    output: true
    permalink: /projects/:path/

author:
  name: "Jose Moreno"
  avatar: "/assets/images/profile.jpg"
  bio: "Computer Science student focused on software engineering, career development, and system design."
  location: "Fort Worth, Texas, USA"

  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Joseamorenojr"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jose-moreno-95b827185/"
